database:
  host: "localhost"
  port: 3306
  database: "giftbox"
  username: "root"
  password: "password"

expiration-check-interval: 600

# Enable debug logging (default: false)
debug: false

messages:
  prefix: "&f[&d선물함&f] "
  no-permission: "&c이 명령어를 사용할 권한이 없습니다."
  gift-sent: "&a손에 든 아이템을 &e%player%&a님에게 성공적으로 보냈습니다."
  player-not-found: "&c플레이어 &e%player%&c님을 찾을 수 없습니다."
  no-item-in-hand: "&c아이템을 보내려면 손에 아이템을 들고 있어야 합니다."
  invalid-command-usage: "&c잘못된 명령어 사용법입니다. 사용법: %usage%"
  invalid-number: "&c만료 시간은 유효한 숫자여야 합니다."
  inventory-full: "&c인벤토리가 가득 찼습니다. 선물을 받으려면 공간을 확보해주세요."
  gift-claimed: "&a선물을 성공적으로 수령했습니다."
  all-gifts-claimed: "&a&e%amount%&a개의 선물을 성공적으로 수령했습니다. 인벤토리가 가득 찼다면 일부 아이템은 수령되지 않았을 수 있습니다."
  no-gifts-to-claim: "&c선물함에 수령할 수 있는 선물이 없습니다."
  join-notification: "&a&e%amount%&a개의 선물이 당신을 기다리고 있습니다! &e/우편함&a을 입력하여 확인하세요."
  gift-expired: "&c이 선물은 만료되어 수령할 수 없습니다."
  concurrent-claim-error: "&c이미 수령을 처리 중입니다. 잠시 기다려주세요."
  gui-title: "선물함 (페이지: %page%)"
  loading-item-name: "&7로딩 중..."
  claim-all-item-name: "&a[ 아이템 모두 받기 ]"
  claim-all-item-lore:
    - "&7클릭 시 수령 가능한 모든 선물을"
    - "&7한 번에 받습니다."
  gift-item-lore:
    - "&f"
    - "&7보낸 사람: &e%sender%"
    - "&7수량: &e%amount%"
    - "&7받은 날짜: &e%date%"
    - "&7만료 기한: &e%expire%"
  expire-never: "영구 보관"
  gui-message-cooldown: 0.2
  loading-error: "&c선물함을 불러오는 중 오류가 발생했습니다. 다시 시도해주세요."